apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-basic
  labels:
    app: daemonset-basic
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: daemonset-basic
  template:
    metadata:
      labels:
        app: daemonset-basic
    spec:
      containers:
      - name: application-container
        image: repocurso/nginx:1.14.2
