apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "PriorityClass del curso"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-with-priority-class
spec:
  priorityClassName: high-priority
  containers:
  - name: application-container
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "700m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "2Gi"
