apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-without-tolerations
  labels:
    env: qualify
spec:
  containers:
  - name: application-container
    image: repocurso/nginx
    imagePullPolicy: IfNotPresent
