apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-clusterrole2-agg2
  labels:
    rbac.curso.com/aggregate: "true"
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
