apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-clusterrolebinding2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-clusterrole2
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: api-access1
  namespace: proyecto1
