-- Ejemplo de archivo YAML
apiVersion: v1
kind: Pod
metadata:
  name: pod-operator
  namespace: proyecto1
spec:
  serviceAccountName: api-access1
  containers:
  - name: operator
    image: repocurso/nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: proyecto2
spec:
  containers:
  - name: test
    image: repocurso/nginx:latest
    ports:
    - containerPort: 80
