apiVersion: v1
kind: Pod
metadata:
  name: nginx-ejm1
  labels:
    app: nginx1
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - name: nginx-port
      containerPort: 80
