apiVersion: v1
kind: Pod
metadata:
  name: nginx-ejm
  labels:
    app: nginx1
spec:
  containers:
  - name: nginx-container
    image: repocurso/nginx:latest
    ports:
    - name: nginx-port
      containerPort: 80
