apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: app-web-canary1 
  labels:
    app: app-web2
    version: v1
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: app-web2 
      version: v1
  template: 
    metadata: 
      labels: 
        app: app-web2 
        version: v1
    spec: 
      containers:
      - name: contenedor
        image: repocurso/httpd:latest
        ports:
        - containerPort: 80
