apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-strategies4
  labels:
    app: nginx-app-strategies4
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app-strategies4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: nginx-app-strategies4
    spec:
      containers:
      - image: repocurso/nginx:v1
        name: nginx
