apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: app-web-green
  labels:
    app: app-web
    version: v2
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: app-web 
      version: v2
  template: 
    metadata: 
      labels: 
        app: app-web 
        version: v2
    spec: 
      containers:
      - name: contenedor
        image: repocurso/nginx:latest
        ports:
        - containerPort: 80
