apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  labels:
    app: app-web
spec:
  type: NodePort
  selector:
    app: app-web
    version: v1
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30201
