apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-strategies3
  labels:
    app: nginx-app-strategies3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app-strategies3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-app-strategies3
    spec:
      containers:
      - image: repocurso/nginx:v1
        name: nginx
