apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: app-web-canary2
  labels:
    app: app-web2
    version: v2
spec: 
  replicas: 0 
  selector: 
    matchLabels: 
      app: app-web2 
      version: v2
  template: 
    metadata: 
      labels: 
        app: app-web2 
        version: v2
    spec: 
      containers:
      - name: contenedor
        image: nginx:latest
        ports:
        - containerPort: 80
