apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-strategies2
  labels:
    app: nginx-app-strategies2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app-strategies2
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-app-strategies2
    spec:
      containers:
      - image: repocurso/nginx:v1
        name: nginx
