apiVersion: v1
kind: Service
metadata:
  name: app-web-service
  labels:
    app: app-web2
spec:
  type: NodePort
  selector:
    app: app-web2
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30202
