apiVersion: batch/v1
kind: CronJob
metadata:
  name: mensaje-cronjob-basic
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: task-cronjob-basic
            image: repocurso/busybox
            command:
            - /bin/sh
            - -c
            - date; echo 'Curso k8s - CronJobs';
