apiVersion: batch/v1
kind: CronJob
metadata:
  name: mensaje-cronjob-history
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: task-cronjob-history
            image: repocurso/busybox:latest
            command: ["/bin/sh", "-c", "echo Curso k8s - CronJobs-History"]
