apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set-demo
  labels:
    app: app-set-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-set-demo
  template:
    metadata:
      labels:
        app: app-set-demo
    spec:
      containers:
      - name: app-demo-container
        image: repocurso/nginx:1.7.8
        ports:
        - containerPort: 80
