apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
spec:
  containers:
  - name: nginx-application
    image: nginx:latest
    ports:
    - name: nginx-port
      containerPort: 80
    envFrom:
    - configMapRef:
        name: config-map
    - secretRef:
        name: config-secret
