apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: labels-demo2 
  labels: 
    app: labels-demo2 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: labels-demo2
  template: 
    metadata: 
      labels: 
        app: labels-demo2 
    spec: 
      containers:
       - name: memcached 
         image: repocurso/memcached
