apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql-sts
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-sts
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 999
      containers:
      - name: mysql
        image: repocurso/mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: password        
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 256Mi
