apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      app: ubuntu-demo-vpa
  replicas: 2
  template:
    metadata:
      labels:
        app: ubuntu-demo-vpa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: ubuntu-container
          image: repocurso/ubuntu-slim:0.1
          resources:
            requests:
              cpu: 50m
              memory: 25Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"
