apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-demo-vpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo-vpa
  template:
    metadata:
      labels:
        app: nginx-demo-vpa
    spec:
      containers:
      - name: nginx-container
        image: repocurso/nginx:1.7.8
        ports:
        - containerPort: 80
