apiVersion: v1
kind: Pod
metadata:
  name: live-ready-nginx-failed
  labels:
    app: web-nginx
spec:
  containers:
  - name: nginx
    image: repocurso/nginx:alpine
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /curso
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
