apiVersion: v1
kind: Pod
metadata:
  name: live-ready-basic
spec:
  containers:
  - name: liveness-readiness
    image: repocurso/redis:latest
    ports:
    - containerPort: 6379
    livenessProbe:
      tcpSocket:
        port: 6379
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
    readinessProbe:
      exec:
        command: 
          - "redis-cli"
          - "ping"
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
