apiVersion: v1
kind: Pod
metadata:
  name: busybox-dns
  namespace: default
  labels:
    app: busybox-dns
spec:
  containers:
  - image: repocurso/busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
