apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  type: NodePort
  selector:
    app: echoserver
  ports:
  - port: 5588
    targetPort: 8080
    nodePort: 30101
