apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pattern
spec:
  volumes:
    - name: nginx-logs
      emptyDir: {}
  containers:
    - name: application-container
      image: nginx
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
    - name: sidecar-container
      image: busybox
      command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 20; done"]
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
