apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-drain
  labels:
    app: app-demo-drain
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-demo-drain
  template:
    metadata:
      labels:
        app: app-demo-drain
    spec:
      containers:
      - name: app-demo-drain-container
        image: repocurso/nginx:1.7.8
