apiVersion: v1
kind: Pod
metadata:
  name: pod-secret2
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: confidential-data-secret2
  containers:
  - name: application-container
    image: redis:latest
    volumeMounts:
    - name: secret-volume
      mountPath: "/tmp/data"
      readOnly: true
