apiVersion: v1
kind: Pod
metadata:
  name: downward-api-container
spec:
  containers:
    - name: application
      image: repocurso/busybox
      command: ["sh", "-c", "while true; do echo; if [[ -e /podinfo/pod_cpu ]]; then echo -n 'cpu: ';cat /podinfo/pod_cpu; fi; if [[ -e /podinfo/pod_memory ]]; then echo -n ' memory: ';cat /podinfo/pod_memory; fi; sleep 5; done"]
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: podinfo
          mountPath: /podinfo
          readOnly: false
  volumes:
  - name: podinfo
    downwardAPI:
      defaultMode: 420
      items:
        - path: "pod_cpu"
          resourceFieldRef:
            containerName: application
            resource: limits.cpu
            divisor: 1m
        - path: "pod_memory"
          resourceFieldRef:
            containerName: application
            resource: limits.memory
            divisor: 1Ki
