apiVersion: v1
kind: Pod
metadata:
  name: nginx-config
spec:
  containers:
  - name: nginx
    image: repocurso/nginx:latest
    ports:
    - name: nginx-port
      containerPort: 80
    env:
    - name: CONF_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: CONF_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: CONF_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
