apiVersion: v1
kind: Pod
metadata:
  name: pod-secret3
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: confidential-data-secret3 
      items:
      - key: username
        path: properties/users
      defaultMode: 0400
  containers:
  - name: application-container
    image: redis:latest
    volumeMounts:
    - name: secret-volume
      mountPath: "/tmp/data"
      readOnly: true
