apiVersion: v1
kind: Pod
metadata:
  name: pod-secret1
spec:
  containers:
  - name: application-container
    image: repocurso/redis:latest
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: confidential-data-secret1
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: confidential-data-secret1
          key: password
  restartPolicy: Never
