apiVersion: v1
kind: Pod
metadata:
  name: downward-api-pod
spec:
  containers:
  - name: nginx
    image: repocurso/nginx:latest
    ports:
    - name: nginx-port
      containerPort: 80
    volumeMounts:
    - name: info
      mountPath: /pod/info
  volumes:
  - name: info
    downwardAPI:
      items:
        - path: podname
          fieldRef:
            fieldPath: metadata.name
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
