apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: proyecto2
  labels:
    project: proyecto2
    app: app-conexion
    type: client
spec:
  containers:
  - name: client
    image: repocurso/erase-una-vez-2:0.1.0
    command:
    - client
    env:
    - name: SERVER_URL
      value: "http://server.proyecto1.svc.cluster.local:8000"
    - name: ENDPOINT
      value: "/echo"
    - name: SLEEP_TIME
      value: "3"
