apiVersion: v1
kind: Pod
metadata:
  name: quota2-demo 
spec:
  containers:
  - name: contenedor
    image: repocurso/nginx:latest
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
