apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: proyecto1
  labels:
    project: proyecto1
    app: app-conexion
    type: server
spec:
  type: ClusterIP
  selector:
    type: server
  ports:
  - name: http-server
    port: 8000
    protocol: TCP
    targetPort: http-server
