apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo2
spec:
  containers:
  - name: application-container
    image: repocurso/stress1
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"

