apiVersion: v1
kind: Pod
metadata:
  name: message-ipc
spec:
  containers:
  - name: producer-container
    image: repocurso/message-ipc
    command: ["./ipc", "-producer"]
  - name: consumer-container
    image: repocurso/message-ipc
    command: ["./ipc", "-consumer"]
  restartPolicy: Never
