apiVersion: v1
kind: Pod
metadata:
  name: helloworld1
spec:
  containers:
  - name: k8s-demo-helloworld
    image: repocurso/k8s-demo
    ports:
    - name: helloworld-port
      containerPort: 3000
