apiVersion: v1
kind: Pod
metadata:
  name: memory-demo1
spec:
  containers:
  - image: repocurso/stress2
    imagePullPolicy: Always
    name: application-container
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
