apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: nginx-deploy-nfs
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy-nfs
  template:
    metadata:
      labels:
        app: nginx-deploy-nfs
    spec:
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.100.10
          path: /mnt/nfs-general/nginx    
      containers: 
      - name: mysql 
        image: repocurso/nginx:latest
        volumeMounts: 
        - name: nfs-volume
          mountPath: /usr/share/nginx/html/ 
