apiVersion: v1
kind: Pod
metadata:
  name: storage-app-nfs-sc
  labels:
    name: storage-app-nfs-sc
spec:
  volumes:
    - name: nginx-persistent-storage
      persistentVolumeClaim:
        claimName: storage-class-pvc
  containers:
  - name: nginx-container
    image: repocurso/nginx:alpine
    ports:
      - containerPort: 80
        name: nginx-port
    volumeMounts:
      - name: nginx-persistent-storage
        mountPath: /usr/share/nginx/html
