apiVersion: v1 
kind: Pod 
metadata: 
  name: business-app1
spec: 
  volumes: 
  - name: logs-volume 
    emptyDir: {} 
  containers: 
  - image: repocurso/nginx 
    name: nginx 
    volumeMounts: 
    - mountPath: /var/logs 
      name: logs-volume
