apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: data-pv2 
  labels:
    pv: volume2
spec: 
  capacity: 
    storage: 1Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: /tmp/data-pv2
