apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: data-pvc2 
spec: 
  selector:
    matchLabels:
      pv: volume2
  accessModes: 
    - ReadWriteOnce 
  storageClassName: "" 
  resources: 
    requests: 
      storage: 256Mi
